project:
  type: website
  output-dir: docs

website:
  title: "Tidy Data & Visualisation with R"
  page-navigation: true
  page-footer: "Copyright 2022, Ramiro Magno & Isabel Duarte" 
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - requirements.qmd
      - trainers.qmd
  sidebar:
    style: "docked"
    search: true
    contents: 
      - setup.qmd
      - raw_data.qmd
      - data_tidying.qmd
      - data_visualisation.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

